// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    INotoBomb: typeof import('~icons/noto/bomb')['default']
  }
}

export { }
